// Generated by CoffeeScript 1.4.0
(function() {
  var Jscii, charLen, chars, getChar, rgbToHsv;

  navigator.getMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;

  Jscii = (function() {

    function Jscii(videoContainer) {
      var h, self, w;
      self = this;
      this.videoContainer = videoContainer;
      this.video = document.querySelector('video');
      this.imgCanvas = document.createElement('canvas');
      this.imgCtx = this.imgCanvas.getContext('2d');
      this.videoCanvas = document.createElement('canvas');
      this.videoCtx = this.videoCanvas.getContext('2d');
      this.videoCanvas.width = this.width = w = 150;
      this.videoCanvas.height = this.height = h = w * 3 / 4;
      navigator.getMedia({
        video: true,
        audio: true
      }, function(localMediaStream) {
        var url;
        url = window.URL || window.webkitURL;
        self.video.src = url.createObjectURL(localMediaStream);
        self.stream = localMediaStream;
        this.videoTimer = setInterval(function() {
          return self.renderVideo();
        }, 20);
        return self.video.onloadedmetadata = function(e) {
          return console.log(e);
        };
      }, function(err) {
        return console.log("The following error occured: " + err);
      });
    }

    Jscii.prototype.stopRender = function() {
      return clearInterval(this.videoTimer);
    };

    Jscii.prototype.renderVideo = function() {
      if (this.stream) {
        this.videoCtx.drawImage(this.video, 0, 0, this.width, this.height);
        this.data = this.videoCtx.getImageData(0, 0, this.width, this.height).data;
        return this.videoContainer.innerHTML = this.toString(this.data, this.width, this.height);
      }
    };

    Jscii.prototype.renderImage = function(img, container) {
      var imgObj,
        _this = this;
      if (typeof container === 'string') {
        container = document.getElementById(container);
      }
      if (typeof img === 'string') {
        if ((imgObj = document.getElementById(img)) && imgObj.tagName === 'IMG') {
          img = imgObj;
        }
      }
      return (this.img = img).addEventListener('load', function() {
        return _this._imageLoaded(container);
      });
    };

    Jscii.prototype._imageLoaded = function(container) {
      var data, h, w;
      this.imgCanvas.width = w = 100;
      this.imgCanvas.height = h = 100 * this.img.height / this.img.width;
      this.imgCtx.drawImage(this.img, 0, 0, w, h);
      data = this.imgCtx.getImageData(0, 0, w, h).data;
      return container.innerHTML = this.toString(data, w, h);
    };

    Jscii.prototype.toString = function(d, width, height) {
      var i, len, str, _fn, _i;
      len = width * height - 1;
      str = '';
      _fn = function(i) {
        var hsv, rgb, val;
        if (i % width === 0) {
          str += '<br>';
        }
        rgb = [d[i = i * 4], d[i + 1], d[i + 2]];
        hsv = rgbToHsv(rgb);
        val = hsv[2];
        return str += getChar(val);
      };
      for (i = _i = 0; 0 <= len ? _i <= len : _i >= len; i = 0 <= len ? ++_i : --_i) {
        _fn(i);
      }
      return str;
    };

    return Jscii;

  })();

  rgbToHsv = function(rgb) {
    var b, d, g, h, max, min, r, s, v, _ref;
    r = rgb[0] / 255;
    g = rgb[1] / 255;
    b = rgb[2] / 255;
    v = max = Math.max(r, g, b);
    min = Math.min(r, g, b);
    d = max - min;
    s = max === 0 ? 0 : d / max;
    if (max === min) {
      h = 0;
    } else {
      if (max === r) {
        h = (g - b) / d + ((_ref = g < b) != null ? _ref : {
          6: 0
        });
      } else if (max === g) {
        h = (b - r) / d + 2;
      } else if (max === b) {
        h = (r - g) / d + 4;
      }
      h *= 60;
    }
    return [h, s, v];
  };

  getChar = function(val) {
    return chars[parseInt(val * charLen, 10)];
  };

  chars = ['@', '#', '$', '%', '*', '!', '=', ';', ':', '~', '-', ',', '.', '&nbsp;', '&nbsp;'];

  charLen = 14;

  window.Jscii = Jscii;

}).call(this);
